
//--------------------------------------------------------------------------------
// Class Instance Information
//--------------------------------------------------------------------------------
#define CLASS_ID_java_lang_Object 0
#define CLASS_ID_java_lang_String 1
#define CLASS_ID__Z 4
#define CLASS_ID__C 5
#define CLASS_ID__B 8
#define CLASS_ID__I 10
#define CLASS_ID_java_lang_Class 15
#define CLASS_ID__Ljava_lang_Object 16
#define CLASS_ID__Ljava_lang_Class 17
#define CLASS_ID_thinj_regression_AllTests 18
#define CLASS_ID_java_lang_System 19
#define CLASS_ID_java_io_PrintStream 20
#define CLASS_ID_java_lang_OutOfMemoryError 21
#define CLASS_ID_java_io_Serializable 22
#define CLASS_ID_java_lang_NullPointerException 23
#define CLASS_ID_java_lang_RuntimeException 24
#define CLASS_ID_java_lang_Exception 25
#define CLASS_ID_java_lang_Throwable 26
#define CLASS_ID_java_lang_NegativeArraySizeException 27
#define CLASS_ID_java_lang_ArrayIndexOutOfBoundsException 28
#define CLASS_ID_java_lang_StringBuilder 29
#define CLASS_ID__Ljava_lang_String 30
#define CLASS_ID_java_lang_ArithmeticException 31
#define CLASS_ID_java_lang_IndexOutOfBoundsException 32
#define CLASS_ID_java_lang_VirtualMachineError 33
#define CLASS_ID_java_lang_Error 34
#define CLASS_ID_thinj_regression_exceptions_ThrowException 35
#define CLASS_ID_thinj_regression_Regression 36
#define CLASS_ID_thinj_regression_exceptions_ExceptionProxying 37
#define CLASS_ID_thinj_regression_exceptions_TestNullPointerException 38
#define CLASS_ID_java_lang_ClassCastException 39
#define CLASS_ID_thinj_regression_exceptions_ExIALOAD 40
#define CLASS_ID_thinj_regression_exceptions_ExIALOAD$MyInterface 41
#define CLASS_ID_java_util_Arrays 42

//--------------------------------------------------------------------------------
// Method Attributes
//--------------------------------------------------------------------------------
#define LINK_ID_java_lang_String__init____C_V 11
#define LINK_ID_java_lang_String_length___I 12
#define LINK_ID_java_lang_String_valueOf__Ljava_lang_Object__Ljava_lang_String_ 2
#define LINK_ID_java_lang_String_getChars__II_CI_V 13
#define LINK_ID_java_lang_String_toString___Ljava_lang_String_ 6
#define LINK_ID_java_lang_String_hashCode___I 14
#define LINK_ID_java_lang_Object__init____V 4
#define LINK_ID_java_lang_Object_hashCode___I 14
#define LINK_ID_java_lang_Object_getClass___Ljava_lang_Class_ 0
#define LINK_ID_java_lang_Object_toString___Ljava_lang_String_ 6
#define LINK_ID_java_lang_Class__clinit____V 22
#define LINK_ID_java_lang_Class_getAllClasses____Ljava_lang_Class_ 19
#define LINK_ID_java_lang_Class_getName___Ljava_lang_String_ 1
#define LINK_ID_java_lang_Class_toString___Ljava_lang_String_ 6
#define LINK_ID_thinj_regression_AllTests_main___V 25
#define LINK_ID_java_lang_System__clinit____V 22
#define LINK_ID_java_io_PrintStream__init____V 4
#define LINK_ID_java_io_PrintStream_outStringLf__Ljava_lang_String__V 27
#define LINK_ID_java_io_PrintStream_println__Ljava_lang_String__V 24
#define LINK_ID_java_lang_OutOfMemoryError__clinit____V 22
#define LINK_ID_java_lang_OutOfMemoryError__init____V 4
#define LINK_ID_java_lang_OutOfMemoryError_getInstance___Ljava_lang_OutOfMemoryError_ 18
#define LINK_ID_java_lang_NullPointerException__init___Ljava_lang_String__V 3
#define LINK_ID_java_lang_NullPointerException__init____V 4
#define LINK_ID_java_lang_RuntimeException__init___Ljava_lang_String__V 3
#define LINK_ID_java_lang_RuntimeException__init____V 4
#define LINK_ID_java_lang_Exception__init___Ljava_lang_String__V 3
#define LINK_ID_java_lang_Exception__init____V 4
#define LINK_ID_java_lang_Throwable__init____V 4
#define LINK_ID_java_lang_Throwable__init___Ljava_lang_String__V 3
#define LINK_ID_java_lang_Throwable_getStackTraceElement__I_I 39
#define LINK_ID_java_lang_Throwable_getStackTraceDepth___I 37
#define LINK_ID_java_lang_Throwable_toString___Ljava_lang_String_ 6
#define LINK_ID_java_lang_NegativeArraySizeException__init____V 4
#define LINK_ID_java_lang_ArrayIndexOutOfBoundsException__init___I_V 10
#define LINK_ID_java_lang_StringBuilder__init___Ljava_lang_String__V 3
#define LINK_ID_java_lang_StringBuilder_append__Ljava_lang_String__Ljava_lang_StringBuilder_ 16
#define LINK_ID_java_lang_StringBuilder_append__Ljava_lang_Object__Ljava_lang_StringBuilder_ 42
#define LINK_ID_java_lang_StringBuilder_append__I_Ljava_lang_StringBuilder_ 17
#define LINK_ID_java_lang_StringBuilder_toString___Ljava_lang_String_ 6
#define LINK_ID_java_lang_ArithmeticException__init___Ljava_lang_String__V 3
#define LINK_ID_java_lang_IndexOutOfBoundsException__init___Ljava_lang_String__V 3
#define LINK_ID_java_lang_VirtualMachineError__init____V 4
#define LINK_ID_java_lang_Error__init____V 4
#define LINK_ID_thinj_regression_exceptions_ThrowException_test1___V 53
#define LINK_ID_thinj_regression_exceptions_ThrowException_testHelper___V 45
#define LINK_ID_thinj_regression_exceptions_ThrowException_test2___V 54
#define LINK_ID_thinj_regression_exceptions_ThrowException_test3___V 55
#define LINK_ID_thinj_regression_exceptions_ThrowException_test4___V 56
#define LINK_ID_thinj_regression_exceptions_ThrowException_test5___V 57
#define LINK_ID_thinj_regression_exceptions_ThrowException_test6Helper___V 48
#define LINK_ID_thinj_regression_exceptions_ThrowException_test6___V 58
#define LINK_ID_thinj_regression_exceptions_ThrowException_test7Helper2___V 51
#define LINK_ID_thinj_regression_exceptions_ThrowException_test7Helper1___V 52
#define LINK_ID_thinj_regression_exceptions_ThrowException_test7___V 59
#define LINK_ID_thinj_regression_exceptions_ThrowException_main___V 25
#define LINK_ID_thinj_regression_Regression_verify__Z_V 44
#define LINK_ID_thinj_regression_exceptions_ExceptionProxying_testExceptionProxy___V 46
#define LINK_ID_thinj_regression_exceptions_TestNullPointerException_test1___V 53
#define LINK_ID_thinj_regression_exceptions_TestNullPointerException_test2___V 54
#define LINK_ID_thinj_regression_exceptions_TestNullPointerException_main___V 25
#define LINK_ID_java_lang_ClassCastException__init____V 4
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_get__I_I 63
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_get___I 64
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_iaload___V 67
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_aaload___V 68
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_baload___V 69
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_caload___V 70
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_iastore___V 71
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_aastore___V 72
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_bastore___V 73
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_castore___V 74
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_idiv___V 75
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_irem___V 76
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_getfield___V 77
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_putfield___V 78
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_invokespecial___V 79
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_invokevirtual___V 80
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_invokeinterface___V 81
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_newarray___V 82
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_anewarray___V 83
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_arraylength___V 84
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_athrow___V 85
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_checkcast___V 86
#define LINK_ID_thinj_regression_exceptions_ExIALOAD_main___V 25
#define LINK_ID_thinj_regression_exceptions_ExIALOAD$MyInterface_foobar___V 65
#define LINK_ID_java_util_Arrays_hashCode___C_I 7
#define LINK_ID_thinj_regression_AllTests__jvminit____V 88
